# Configuration for the SRM RAG system

# --- Mode Selection ---
# Select the active mode: "low", "medium", or "high"
current_mode: "low"

# --- General Settings ---
docs_path: "docs"
index_path: "index"
ollama_model: "llama3.2:3b" # Or "phi3", "llama3.1"

# --- RAG Mode Configurations ---
modes:
  # Low mode: Fastest response, lowest quality.
  # Disables reranking and multi-stage generation for speed.
  low:
    embedding_model: "all-MiniLM-L6-v2"
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    
    # Retrieval settings
    top_k_bm25: 5
    top_k_faiss: 5
    top_k_reranked: 3
    
    # Advanced features (mostly disabled for speed)
    enable_multi_query_generation: false
    enable_reranking: false
    enable_multi_stage_generation: false
    
    # Context management
    max_context_length: 4000

  # Medium mode: Balanced speed and quality.
  # Enables reranking and other key features for better accuracy.
  medium:
    embedding_model: "all-MiniLM-L6-v2"
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    
    # Retrieval settings
    top_k_bm25: 8
    top_k_faiss: 8
    top_k_reranked: 5
    
    # Advanced features
    enable_multi_query_generation: true
    enable_reranking: true
    enable_multi_stage_generation: true
    
    # Context management
    max_context_length_simple: 6000
    max_context_length_medium: 8000
    max_context_length_complex: 12000

  # High mode: Best quality, slowest response.
  # Uses more candidates for retrieval and reranking for maximum thoroughness.
  high:
    embedding_model: "all-MiniLM-L6-v2" # Consider a more powerful model for high mode
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    
    # Retrieval settings
    top_k_bm25: 12
    top_k_faiss: 12
    top_k_reranked: 7
    
    # Advanced features (all enabled)
    enable_multi_query_generation: true
    enable_reranking: true
    enable_multi_stage_generation: true
    
    # Context management
    max_context_length_simple: 8000
    max_context_length_medium: 10000
    max_context_length_complex: 16000
