# Configuration for the SRM RAG system

# --- Mode Selection ---
# Select the active mode: "low", "medium", or "high"
current_mode: "low"

# --- General Settings ---
docs_path: "docs"
index_path: "index"

# --- Model Configuration ---
# Change models from this single location - they will be used throughout the application
ollama_model: "phi3:3.8b"  # LLM model for answer generation (e.g., "phi3:3.8b", "phi3:14b", "mistral:latest")
                              # Note: Embedding and reranker models are configured per mode below

use_direct_results: false  # Set to true to return raw search results without LLM processing
strict_mode: true  # Set to true to enable hallucination detection and validation

# --- RAG Mode Configurations ---
modes:
  # Low mode: Optimized for low-spec CPU systems without GPU
  # Minimal resource usage while maintaining basic RAG functionality
  low:
    # Embedding model for semantic search (change here to use throughout processing/search)
    embedding_model: "all-MiniLM-L6-v2"  # Best balance of speed/quality for CPU
                                          # For very low-spec systems, consider: "all-distilroberta-v1"
    # Reranker model for result ranking
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-2-v2"  # Lightweight reranker

    # Retrieval settings - increased for better coverage
    top_k_bm25: 6        # Increased to search more documents
    top_k_faiss: 6       # Increased to search more documents
    top_k_reranked: 3    # Increased to return more results

    # Advanced features - enable diversity for better multi-document search
    enable_multi_query_generation: false  # Disabled - saves CPU cycles
    enable_reranking: false               # Disabled - heavy CPU operation
    enable_multi_stage_generation: false  # Disabled - not needed for low mode
    enable_diversity_selection: true      # ENABLED - ensures diverse results
    enable_document_diversity: true       # ENABLED - searches across multiple documents
    enable_strict_mode: false             # Disabled for performance in low mode

    # Performance optimizations for maximum speed
    batch_size: 8                         # Even smaller batches for speed
    max_concurrent_searches: 1            # Sequential processing
    embedding_cache_size: 50              # Minimal memory usage

    # Context management - maximum speed optimization
    max_context_length: 1200              # Ultra-fast context window
    max_context_length_simple: 1500       # Minimal for simple queries
    max_context_length_medium: 2000       # Very fast for medium queries
    max_context_length_complex: 2500      # Still fast for complex queries

  # Medium mode: Balanced speed and quality.
  # Enables reranking and other key features for better accuracy.
  medium:
    # Embedding model for semantic search
    embedding_model: "all-MiniLM-L6-v2"
    # Reranker model for result ranking (slightly better than low mode)
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    
    # Retrieval settings
    top_k_bm25: 10
    top_k_faiss: 10
    top_k_reranked: 7
    
    # Advanced features
    enable_multi_query_generation: true
    enable_reranking: true
    enable_multi_stage_generation: true
    
    # Context management - optimized for performance
    max_context_length_simple: 4000
    max_context_length_medium: 6000
    max_context_length_complex: 8000

  # High mode: Best quality, slowest response.
  # Uses more candidates for retrieval and reranking for maximum thoroughness.
  high:
    # Embedding model for semantic search (consider upgrading to a more powerful model)
    embedding_model: "all-MiniLM-L6-v2"  # Options: "all-mpnet-base-v2", "multi-qa-mpnet-base-dot-v1"
    # Reranker model for result ranking
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    
    # Retrieval settings
    top_k_bm25: 12
    top_k_faiss: 12
    top_k_reranked: 7
    
    # Advanced features (all enabled)
    enable_multi_query_generation: true
    enable_reranking: true
    enable_multi_stage_generation: true
    
    # Context management - optimized for performance
    max_context_length_simple: 5000
    max_context_length_medium: 7000
    max_context_length_complex: 10000
