# Configuration for the SRM RAG CLI

# Paths
docs_path: "docs"
index_path: "index"

# Models
embedding_model: "all-MiniLM-L6-v2"
reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
ollama_model: "llama3.2:3b" # Or "phi3"

# Indexing settings
chunk_size: 1024
chunk_overlap: 128

# Retrieval settings
top_k_bm25: 5
top_k_faiss: 5
top_k_reranked: 3
